### ISSUE TITLE
[FEATURE] Barcodes Filter

### ISSUE THREAD

**Issue by alistairsykes** [brightec/KBarcode#1]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Similar to the already implemented sort feature, it would be great to add a filter, which would enable functionality such as only returning barcodes within a certain area (i.e. viewfinder).

It would be great to provide a base class (similar to BarcodeComparator.kt) which can provide the FrameMetadata, in order to enable more functionality.

**Describe alternatives you've considered**
This can be done manually within the implementation listener, but would be simpler if it was integrated into the library.

**Additional context**
None

**Comment by falkontre** [comment]
In the android manifest the "uses-feature" forces the application that uses this library to use them.
An app could have the barcode scanning as optional feature, but by forcing these feature, the app cannot be installed because google play filters devices not matching.

A possible solution could be a change of:
`<uses-feature android:name="android.hardware.camera" />`
`<uses-feature android:name="android.hardware.camera.autofocus" />`

in:
`<uses-feature android:name="android.hardware.camera" android:required="false"/>`
`<uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>`

**Comment by alistairsykes** [comment]
> In the android manifest the "uses-feature" forces the application that uses this library to use them.
> An app could have the barcode scanning as optional feature, but by forcing these feature, the app cannot be installed because google play filters devices not matching.
> 
> A possible solution could be a change of:
> `<uses-feature android:name="android.hardware.camera" />`
> `<uses-feature android:name="android.hardware.camera.autofocus" />`
> 
> in:
> `<uses-feature android:name="android.hardware.camera" android:required="false"/>`
> `<uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>`

I have raised this as new issue. Good spot. #2

**Comment by alistairsykes** [comment]
This library is no longer maintained. Marking `wontfix`
