### ISSUE TITLE
[FEATURE] Black screen when Camera permission denied.

### ISSUE THREAD

**Issue by EFEXP** [brightec/KBarcode#36]
Thank you for providing awesome library :smiley:
**Is your feature request related to a problem? Please describe.**
When I cleared data and reinstalled an app using Barcode view,it kept black screen without any warning and error. So,it took a lot of time to solve. 
Though it was stupid error due to no Camera Permission, but sometimes we forget:cry:

**Describe the solution you'd like**
Throw a Exception when it has no camera permission.

**Comment by alistairsykes** [comment]
Hi @EFEXP. Glad to be able to provide this library for you.

I'm sorry that you didn't spot you needed to handle permissions.
As explained [here](https://github.com/brightec/KBarcode/wiki/Reference#permissions) we want to avoid handling permissions within the library. However you should have seen a log within logcat to the affect of `Application does not have permission to access the camera`.

I don't think it would be appropriate to cause application to crash due to this. Some application may want to be able to handle no permission's flows, and this library crashing would be detrimental to that.

I have updated the [wiki get started](https://github.com/brightec/KBarcode/wiki) page to include  reference to the permission section of wiki. Hopefully this will help to make it clearer.
